# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  jhipserwebflux-app:
    image: jhipserwebflux
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://jhipserwebflux-postgresql:5432/jhipserWebflux
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://jhipserwebflux-postgresql:5432/jhipserWebflux
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  jhipserwebflux-postgresql:
    image: postgres:13.2
    # volumes:
    #   - ~/volumes/jhipster/jhipserWebflux/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipserWebflux
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
